---
title: "Demographics of Multiligual Learners"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      include = TRUE,
                      message = FALSE,
                      fig.width = 8)

pacman::p_load(tidyverse, janitor, readxl, writexl, here, plotly, flextable)
percentage <- function(x){
  paste(round(100*x, 2), "%", sep="")
}

mytable1 <- function(x){
  addmargins(table(x, exclude = NULL, deparse.level = 0))
}

mytable2 <- function(x, y){
  addmargins(table(x, y, exclude = NULL, deparse.level = 0))
}

checkdup <- function(df){
  df %>% group_by(student_no) %>% filter(n() > 1) %>% ungroup() %>% arrange(student_no)
}

checkna <- function(df){
  sapply(df, function(x){sum(is.na(x))})
}
```


```{r}
# if (!require('devtools')) install.packages('devtools')
# devtools::install_github('rstudio/leaflet')
```


```{r, layout="l-screen-inset shaded", include = TRUE}

```

```{css, echo=FALSE}
/* Whole document: */
body{
  font-family: Helvetica;
  font-size: 14pt;
}
```


```{r}
ml <- read_xlsx(here("./data/ml.xlsx")) %>%
  mutate(elas = factor(elas,
                       levels = c("English or American Sign Language Only",
                                  "Initial Fluent English Proficient",
                                  "Reclassified Fluent English Proficient",
                                  "English Learner",
                                  "Adult English Learner"),
                       labels = c("EO",
                                  "IFEP",
                                  "RFEP",
                                  "EL",
                                  "EL"))) %>%
  drop_na() %>%
  mutate(typo_desc = typo,
         typo = factor(typo_desc,
                       levels = c("EL 6+ Yrs LTEL",
                                  "EL 4-5 Yrs Potential LTEL",
                                  "EL 4+ Yrs On Track",
                                  "EL 0-3 Yrs",
                                  "EL 0-3 Yrs Newcomer"),
                       labels = c("LTEL",
                                  "PLTEL",
                                  "ELOT",
                                  "NewEL",
                                  "Newcomer")),
         elas = case_when(elas == "EL" ~ typo, 
                          .default = elas)) %>% 
  rename(School = sch,
         ELAS = elas,
         Grade = grade,
         Typology = typo)
```


# A glossary of the terms used on this page

```{r, results="asis", ft.align="left"}
data.frame(ELAS = c("EO",
                    "IFEP",
                    "RFEP",
                    "LTEL",
                    "PLTEL",
                    "ELOT",
                    "NewEL",
                    "Newcomer"),
           Description = c("English or American Sign Language Only",
                           "Initial Fluent English Proficient",
                           "Reclassified Fluent English Proficient",
                           "EL 6+ Yrs LTEL",
                           "EL 4-5 Yrs Potential LTEL",
                           "EL 4+ Yrs On Track",
                           "EL 0-3 Yrs",
                           "EL 0-3 Yrs Newcomer"),
               EL = c("N",
                      "N",
                      "N",
                      "Y",
                      "Y",
                      "Y",
                      "Y",
                      "Y"),
           EverEL = c("N",
                      "N",
                      "Y",
                      "Y",
                      "Y",
                      "Y",
                      "Y",
                      "Y"),
     Multilingual = c("N",
                      "Y",
                      "Y",
                      "Y",
                      "Y",
                      "Y",
                      "Y",
                      "Y")
           ) %>% 
  flextable() %>% 
  bold(part = "header") %>% 
  set_table_properties(width = 0.8, layout = "autofit") %>% 
  bg(bg = "cadetblue3", part = "header") %>% 
  bg(bg = "aliceblue", part = "body")
```


